# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_0t1NJo758XLQrN0KunvajfZ5WwGxFBy
"""

import os
import glob
import json
from datetime import datetime

import pandas as pd
import geopandas as gpd
from shapely.geometry import Point
import streamlit as st
import folium
from streamlit_folium import st_folium

# Install missing libraries if running in Colab
# If you're running this locally, you can use pip install -r requirements.txt
try:
    import streamlit
    import geopandas
    import streamlit_folium
except ImportError:
    !pip install streamlit geopandas streamlit-folium
    # Re-import after installation
    import streamlit as st
    import geopandas as gpd
    import streamlit_folium as st_folium

# -----------------------------
# Page config + styling
# -----------------------------
st.set_page_config(
    page_title="Elgeyo-Marakwet Flood Risk Command Center",
    page_icon="🌊",
    layout="wide",
)

CUSTOM_CSS = """
<style>
/* nicer spacing */
.block-container { padding-top: 1.2rem; padding-bottom: 2rem; }
/* cards */
.kpi-card {
    border: 1px solid rgba(255,255,255,0.10);
    border-radius: 16px;
    padding: 14px 14px;
    background: rgba(255,255,255,0.03);
}
.small-muted { opacity: 0.80; font-size: 0.85rem; }
.section-title { font-size: 1.05rem; font-weight: 700; margin: 0.25rem 0 0.5rem 0; }
hr { border: none; height: 1px; background: rgba(255,255,255,0.10); margin: 1rem 0; }
</style>
"""
st.markdown(CUSTOM_CSS, unsafe_allow_html=True)

st.title("🌊 Flood Risk GIS Command Center — Elgeyo-Marakwet")
st.caption("Built by **Philemon Kibor** (GIS • Data • AI) — DEM hazard + rivers + health infrastructure exposure")

DATA_DIR = "data"

# -----------------------------
# Utilities: robust file finder
# -----------------------------
def pick_path(candidates):
    """Return first existing path from a list of candidates."""
    for p in candidates:
        if p and os.path.exists(p):
            return p
    return None

def find_data_file(preferred_name, must_contain=None, exts=(".geojson", ".csv")):
    """
    Try:
    1) data/preferred_name
    2) root/preferred_name
    3) search any file in data/ matching must_contain
    """
    cands = [
        os.path.join(DATA_DIR, preferred_name),
        preferred_name,
    ]

    # fuzzy search
    search_spaces = []
    if os.path.exists(DATA_DIR):
        for ext in exts:
            search_spaces += glob.glob(os.path.join(DATA_DIR, f"*{ext}"))
    search_spaces += [p for ext in exts for p in glob.glob(f"*{ext}")]

    if must_contain:
        search_spaces = [p for p in search_spaces if must_contain.lower() in os.path.basename(p).lower()]

    cands += search_spaces
    return pick_path(cands)

@st.cache_data(show_spinner=False)
def load_geo(path):
    gdf = gpd.read_file(path)
    if gdf.crs is None:
        gdf = gdf.set_crs("EPSG:4326")
    else:
        gdf = gdf.to_crs("EPSG:4326")
    return gdf

@st.cache_data(show_spinner=False)
def load_facilities_csv(path):
    df = pd.read_csv(path)

    # auto-detect cols
    cols = {c.lower().strip(): c for c in df.columns}
    name_col = cols.get("facility") or cols.get("name") or cols.get("facility_name") or df.columns[0]
    lat_col = cols.get("lat") or cols.get("latitude")
    lon_col = cols.get("lon") or cols.get("longitude") or cols.get("long")

    if lat_col is None or lon_col is None:
        raise ValueError(f"Missing lat/lon columns. Found columns: {list(df.columns)}")

    df = df.rename(columns={name_col: "Facility", lat_col: "lat", lon_col: "lon"}).copy()
    df["lat"] = pd.to_numeric(df["lat"], errors="coerce")
    df["lon"] = pd.to_numeric(df["lon"], errors="coerce")
    df = df.dropna(subset=["lat", "lon"]).copy()

    gdf = gpd.GeoDataFrame(
        df,
        geometry=[Point(xy) for xy in zip(df["lon"], df["lat"])],
        crs="EPSG:4326",
    )
    return gdf

def classify_facility(name: str) -> str:
    n = (name or "").lower()
    if "referral" in n and "hospital" in n:
        return "County Referral Hospital"
    if "sub county hospital" in n or "sub-county hospital" in n or "sub district hospital" in n or "sub-district hospital" in n:
        return "Sub-County Hospital"
    if "hospital" in n:
        return "Hospital"
    if "health centre" in n or "health center" in n:
        return "Health Centre"
    if "dispensary" in n:
        return "Dispensary"
    return "Other"

PRIORITY = {
    "County Referral Hospital": 5,
    "Sub-County Hospital": 4,
    "Hospital": 4,
    "Health Centre": 3,
    "Dispensary": 2,
    "Other": 1,
}

# -----------------------------
# Locate data files
# -----------------------------
boundary_path = find_data_file("elgeyo_marakwet_boundary.geojson", must_contain="boundary")
rivers_path = find_data_file("elgeyo_rivers_osm.geojson", must_contain="rivers")
hazard_path = find_data_file("elgeyo_flood_hazard.geojson", must_contain="hazard")
fac_path = find_data_file("Health_Facilities_Coordinates.csv", must_contain="health", exts=(".csv",))

with st.sidebar:
    st.subheader("⚙️ Controls")

    if st.checkbox("Show debug (files seen)"):
        st.write("Working dir:", os.getcwd())
        st.write("Root files:", sorted([f for f in os.listdir(".") if not f.startswith(".")])[:200])
        if os.path.exists(DATA_DIR):
            st.write("data/ files:", sorted(os.listdir(DATA_DIR))[:200])
        else:
            st.write("data/ folder missing")

    st.markdown("---")
    st.write("**Detected paths**")
    st.code(
        f"boundary: {boundary_path}\n"
        f"rivers:   {rivers_path}\n"
        f"hazard:   {hazard_path}\n"
        f"fac:      {fac_path}\n",
        language="text",
    )

# Validate required files
missing = []
if not boundary_path: missing.append("elgeyo_marakwet_boundary.geojson")
if not rivers_path: missing.append("elgeyo_rivers_osm.geojson")
if not hazard_path: missing.append("elgeyo_flood_hazard.geojson")
if not fac_path: missing.append("Health_Facilities_Coordinates.csv")

if missing:
    st.error(
        "Missing files in your repo. Add these to `data/` (recommended) or the project root:\n\n"
        + "\n".join([f"- {m}" for m in missing])
    )
    st.stop()

# -----------------------------
# Load datasets
# -----------------------------
boundary = load_geo(boundary_path)
rivers = load_geo(rivers_path)
hazard = load_geo(hazard_path)
facilities = load_facilities_csv(fac_path)

# Normalize hazard attribute
if "risk_level" not in hazard.columns:
    for alt in ["Risk", "risk", "hazard", "level", "RISK_LEVEL"]:
        if alt in hazard.columns:
            hazard["risk_level"] = hazard[alt]
            break
if "risk_level" not in hazard.columns:
    hazard["risk_level"] = "Unknown"
hazard["risk_level"] = hazard["risk_level"].astype(str).str.title()

# Add facility level/priority
facilities["Facility_Level"] = facilities["Facility"].astype(str).apply(classify_facility)
facilities["Disaster_Priority"] = facilities["Facility_Level"].map(PRIORITY).fillna(1).astype(int)

# -----------------------------
# Sidebar filtering
# -----------------------------
with st.sidebar:
    st.subheader("🧩 Filters")

    risk_levels = sorted(hazard["risk_level"].unique().tolist())
    default_risks = [r for r in ["High", "Medium", "Low"] if r in risk_levels] or risk_levels
    selected_risks = st.multiselect("Hazard zones to display", risk_levels, default=default_risks)

    facility_levels = sorted(facilities["Facility_Level"].unique().tolist())
    selected_levels = st.multiselect("Facility types", facility_levels, default=facility_levels)

    show_boundary = st.checkbox("Show boundary", True)
    show_rivers = st.checkbox("Show rivers", True)
    show_hazard = st.checkbox("Show hazard zones", True)
    show_fac = st.checkbox("Show facilities", True)

haz_f = hazard[hazard["risk_level"].isin(selected_risks)].copy()
fac_f = facilities[facilities["Facility_Level"].isin(selected_levels)].copy()

# -----------------------------
# Exposure analysis (spatial joins)
# -----------------------------
# Facilities in selected hazard zones
haz_for_join = haz_f[["risk_level", "geometry"]].copy()
fac_join = gpd.sjoin(fac_f, haz_for_join, how="left", predicate="within")
fac_join["risk_level"] = fac_join["risk_level"].fillna("Outside")
fac_join["in_selected_hazard"] = fac_join["risk_level"].ne("Outside")

# Facilities in HIGH hazard (global, not filtered)
haz_high = hazard[hazard["risk_level"] == "High"][["risk_level", "geometry"]].copy()
fac_in_high = gpd.sjoin(fac_f, haz_high, how="inner", predicate="within")

# Summaries
total_fac = len(fac_f)
selected_exposed = int(fac_join["in_selected_hazard"].sum())
high_exposed = len(fac_in_high)
haz_count = len(haz_f)

# -----------------------------
# KPI header
# -----------------------------
k1, k2, k3, k4 = st.columns(4)

k1.markdown(f"""
<div class="kpi-card">
  <div class="section-title">Health Facilities (filtered)</div>
  <div style="font-size: 2rem; font-weight:800;">{total_fac:,}</div>
  <div class="small-muted">Facilities displayed on map</div>
</div>
""", unsafe_allow_html=True)

k2.markdown(f"""
<div class="kpi-card">
  <div class="section-title">Exposed in Selected Hazard</div>
  <div style="font-size: 2rem; font-weight:800;">{selected_exposed:,}</div>
  <div class="small-muted">Facilities inside visible hazard zones</div>
</div>
""", unsafe_allow_html=True)

k3.markdown(f"""
<div class="kpi-card">
  <div class="section-title">Exposed in HIGH Hazard</div>
  <div style="font-size: 2rem; font-weight:800;">{high_exposed:,}</div>
  <div class="small-muted">Critical exposure count</div>
</div>
""", unsafe_allow_html=True)

k4.markdown(f"""
<div class="kpi-card">
  <div class="section-title">Hazard Polygons (filtered)</div>
  <div style="font-size: 2rem; font-weight:800;">{haz_count:,}</div>
  <div class="small-muted">Zones shown on map</div>
</div>
""", unsafe_allow_html=True)

st.markdown("<hr/>", unsafe_allow_html=True)

# -----------------------------
# Tabs
# -----------------------------
tab_map, tab_analytics, tab_reports, tab_about = st.tabs(
    ["🗺️ Map", "📊 Analytics", "📄 Reports", "ℹ️ About"]
)

# -----------------------------
# Map tab
# -----------------------------
with tab_map:
    left, right = st.columns([1.55, 1])

    with left:
        st.subheader("Interactive GIS Map")

        cent = boundary.geometry.centroid.iloc[0]
        m = folium.Map(location=[cent.y, cent.x], zoom_start=9, tiles="CartoDB positron")

        if show_boundary:
            folium.GeoJson(
                boundary,
                name="County Boundary",
                style_function=lambda x: {"color": "#111111", "weight": 3, "fillOpacity": 0.03},
            ).add_to(m)

        if show_rivers:
            # Rivers tooltip safe even if fields missing
            tooltip_fields = [c for c in ["name", "waterway"] if c in rivers.columns]
            tooltip = folium.GeoJsonTooltip(fields=tooltip_fields, aliases=["Name", "Type"][: len(tooltip_fields)], sticky=False) if tooltip_fields else None
            folium.GeoJson(
                rivers,
                name="Rivers/Streams (OSM)",
                style_function=lambda x: {"color": "#1f77b4", "weight": 2},
                tooltip=tooltip,
            ).add_to(m)

        palette = {"High": "#C73E1D", "Medium": "#F18F01", "Low": "#2E86AB", "Unknown": "#7A7A7A"}

        if show_hazard:
            def hz_style(feat):
                lvl = str(feat["properties"].get("risk_level", "Unknown")).title()
                c = palette.get(lvl, palette["Unknown"])
                return {"color": c, "weight": 1.2, "fillColor": c, "fillOpacity": 0.35}

            folium.GeoJson(
                haz_f,
                name="Flood Hazard Zones",
                style_function=hz_style,
                tooltip=folium.GeoJsonTooltip(fields=["risk_level"], aliases=["Risk"], sticky=False)
                if "risk_level" in haz_f.columns else None,
            ).add_to(m)

        if show_fac:
            # facility marker colors
            facility_colors = {
                "County Referral Hospital": "#8B0000",
                "Sub-County Hospital": "#B22222",
                "Hospital": "#DC143C",
                "Health Centre": "#2E8B57",
                "Dispensary": "#1E90FF",
                "Other": "#555555",
            }

            fg = folium.FeatureGroup(name="Health Facilities")
            # create a set for "high hazard exposure" quick lookup
            high_ids = set(fac_in_high.index) if len(fac_in_high) else set()

            for idx, r in fac_f.iterrows():
                lvl = r.get("Facility_Level", "Other")
                base_color = facility_colors.get(lvl, "#555555")
                is_high = idx in high_ids

                # outline red if in high hazard
                ring = "red" if is_high else base_color

                folium.CircleMarker(
                    location=[r.geometry.y, r.geometry.x],
                    radius=6 if is_high else 5,
                    color=ring,
                    weight=3 if is_high else 2,
                    fill=True,
                    fill_color=base_color,
                    fill_opacity=0.95,
                    popup=folium.Popup(
                        f"<b>{r['Facility']}</b>"
                        f"<br>Type: {lvl}"
                        f"<br>Priority: {int(r['Disaster_Priority'])}"
                        f"<br><span style='color:red;'><b>HIGH hazard exposure</b></span>" if is_high else
                        f"<b>{r['Facility']}</b><br>Type: {lvl}<br>Priority: {int(r['Disaster_Priority'])}",
                        max_width=280
                    ),
                ).add_to(fg)

            fg.add_to(m)

        # Legend
        legend_html = """
        <div style="position: fixed; bottom: 40px; left: 40px; background: white; z-index:9999;
                    padding: 10px 12px; border: 2px solid #888; border-radius: 12px; font-size: 13px;">
        <b>Legend</b><br>
        <span style="color:#C73E1D; font-size:18px;">●</span> High hazard<br>
        <span style="color:#F18F01; font-size:18px;">●</span> Medium hazard<br>
        <span style="color:#2E86AB; font-size:18px;">●</span> Low hazard<br>
        <hr style="margin:6px 0;">
        <span style="color:red; font-size:18px;">◯</span> Facility in HIGH hazard<br>
        </div>
        """
        m.get_root().html.add_child(folium.Element(legend_html))

        folium.LayerControl(collapsed=True).add_to(m)
        st_folium(m, height=640, use_container_width=True)

    with right:
        st.subheader("Quick Insights")

        st.markdown("**Exposure by risk (selected filters)**")
        risk_counts = fac_join["risk_level"].value_counts()
        st.bar_chart(risk_counts)

        st.markdown("**Facilities by type**")
        type_counts = fac_f["Facility_Level"].value_counts()
        st.bar_chart(type_counts)

        st.markdown("**Top HIGH-risk facilities (Priority first)**")
        if len(fac_in_high):
            top = fac_in_high.copy()
            top["Facility_Level"] = top["Facility_Level"].astype(str)
            top = top.sort_values(["Disaster_Priority", "Facility"], ascending=[False, True])
            st.dataframe(
                top.drop(columns=["geometry", "index_right"], errors="ignore")[
                    ["Facility", "Facility_Level", "Disaster_Priority", "lat", "lon"]
                ],
                use_container_width=True,
                height=300
            )
        else:
            st.info("No facilities currently fall inside HIGH hazard polygons (based on your hazard model).")

# -----------------------------
# Analytics tab
# -----------------------------
with tab_analytics:
    st.subheader("Analytics & Decision Support")

    a, b = st.columns([1, 1])

    with a:
        st.markdown("### Facilities inside selected hazard zones")
        exposed = fac_join[fac_join["in_selected_hazard"]].copy()
        if len(exposed):
            by_level = exposed["Facility_Level"].value_counts().rename_axis("Facility_Level").reset_index(name="count")
            st.dataframe(by_level, use_container_width=True)
        else:
            st.info("No facilities inside selected hazard zones for the current filters.")

    with b:
        st.markdown("### Summary table (risk × type)")
        pivot = pd.crosstab(fac_join["Facility_Level"], fac_join["risk_level"])
        st.dataframe(pivot, use_container_width=True)

    st.markdown("---")
    st.markdown("### Priority scoring (for response planning)")
    st.write(
        "Priority uses a simple scoring rule: **County Referral Hospital (5)**, **Sub-County/Hospital (4)**, "
        "**Health Centre (3)**, **Dispensary (2)**."
    )

    if len(fac_in_high):
        high_list = fac_in_high.copy()
        high_list = high_list.sort_values(["Disaster_Priority", "Facility"], ascending=[False, True])
        st.dataframe(
            high_list.drop(columns=["geometry", "index_right"], errors="ignore")[
                ["Facility", "Facility_Level", "Disaster_Priority", "lat", "lon"]
            ],
            use_container_width=True
        )
    else:
        st.info("No HIGH-hazard facilities found (based on your hazard zones).")

# -----------------------------
# Reports tab (downloads)
# -----------------------------
with tab_reports:
    st.subheader("Export Reports")

    # 1) Facilities with hazard label (selected)
    out_fac = fac_join.drop(columns=["geometry", "index_right"], errors="ignore").copy()
    st.download_button(
        "⬇️ Download facilities with hazard label (CSV)",
        data=out_fac.to_csv(index=False).encode("utf-8"),
        file_name="elgeyo_facilities_with_hazard.csv",
        mime="text/csv",
    )

    # 2) High hazard facilities
    out_high = fac_in_high.drop(columns=["geometry", "index_right"], errors="ignore").copy()
    st.download_button(
        "⬇️ Download facilities in HIGH hazard (CSV)",
        data=out_high.to_csv(index=False).encode("utf-8"),
        file_name="elgeyo_facilities_high_hazard.csv",
        mime="text/csv",
    )

    # 3) Filtered hazard zones
    haz_bytes = haz_f.to_json().encode("utf-8")
    st.download_button(
        "⬇️ Download filtered hazard zones (GeoJSON)",
        data=haz_bytes,
        file_name="elgeyo_flood_hazard_filtered.geojson",
        mime="application/geo+json",
    )

    st.markdown("---")
    st.markdown("### Project readiness checklist")
    st.write("✅ Real boundary + rivers + hazard polygons + facility coordinates")
    st.write("✅ Exposure analysis + priority ranking")
    st.write("✅ Map + analytics + exportable reports")
    st.write("✅ Streamlit Cloud deployment-ready")

# -----------------------------
# About tab
# -----------------------------
with tab_about:
    st.subheader("About this system")
    st.write(
        "This Flood Risk Command Center integrates:\n"
        "- County boundary (GADM)\n"
        "- Rivers/streams (OpenStreetMap)\n"
        "- DEM-derived flood hazard zones (elevation + proximity)\n"
        "- Health facilities (official coordinates)\n\n"
        "Outputs include exposure analytics, priority ranking, and downloadable reports."
    )
    st.write(f"Build timestamp: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}")

st.success("✅ Dashboard ready. Deploy to Streamlit Cloud and share the link in your portfolio/CV.")